general:
  debugMode: False
  #allowMultpleServerInstances: True
  externalizeTemplates: True

ramdisk:
  drive: "R"
  size: "5G"

server:
  dedicatedYaml: 'esm-dedicated.yaml'
  savegame: 'EsmDediGame'
  #startMode: 'direct'
  startMode: 'launcher'
  gfxMode: True
  launcher:
    maxStartupTimeout: 15

paths:
  install: 'D:\EGS\Empyrion\'
  osfmount: 'C:\Users\Nutzer\Programme\OSFMount\osfmount.com'
  peazip: 'C:\Program Files\PeaZip\res\bin\7z\7z.exe'
  epmremoteclient: ''

foldernames:
  saves: 'Saves'
  games: 'Games'
  backup: 'Backup'
  backupmirrors: 'BackupMirrors'
  backupmirrorprefix: 'rollingBackup_'
  logs: 'Logs'
  dedicatedserver: 'DedicatedServer'
  gamesmirror: 'GamesMirror'
  savegamemirrorpostfix: '_Mirror'
  savegametemplatepostfix: '_Templates'

filenames:
  globaldb: 'global.db'
  buildNumber: 'BuildNumber.txt'
  chatlines: 'hamster_sync_lines.txt'
  dedicatedExe: 'EmpyrionDedicated.exe'
  launcherExe: 'EmpyrionLauncher.exe'

robocopy:
  encoding: 'ansi' #depending on the shell used, it may be necessary to change this to ansi, utf-8, cp1252 or something. This will be passed to subprocess.run(...encoding=...)
  options:
    move: "/MOVE /E /np /ns /nc /nfl /ndl /mt /r:10 /w:10 /unicode"
    copy: "/MIR  /np /ns /nc /nfl /ndl /mt /r:10 /w:10 /unicode"
